# Generated by Django 5.1.7 on 2025-03-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
