# Generated by Django 5.1.7 on 2025-03-17 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alter_alerta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='country',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='institution',
            field=models.CharField(default='No especificado', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerta',
            name='metadata_nota_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='metadata_publicacion_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='presentation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerta',
            name='source_type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='source_url',
            field=models.URLField(default='No especificado', max_length=500),
            preserve_default=False,
        ),
    ]
