# Generated by Django 5.1.7 on 2025-03-21 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_alter_alerta_category_alter_alerta_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la configuración')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('source_type', models.CharField(blank=True, max_length=300, verbose_name='Tipo de fuente')),
                ('category', models.CharField(blank=True, max_length=300, verbose_name='Categoría')),
                ('country', models.CharField(blank=True, max_length=300, verbose_name='País')),
                ('institution', models.CharField(blank=True, max_length=300, verbose_name='Institución')),
                ('days_back', models.IntegerField(default=1, verbose_name='Días hacia atrás')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico para recibir alertas')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=10, verbose_name='Frecuencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Último envío')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='alerta',
            name='unique_alerta_title_date',
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url__isnull', True), ('source_url', ''), _connector='OR'), fields=('title', 'presentation_date'), name='unique_alerta_title_date'),
        ),
        migrations.AddField(
            model_name='emailalertconfig',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='email_configs', to='alertas.keyword', verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='emailalertconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
