name: Run Scrapers Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Ejecutar cada 6 horas
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        
    - name: Crear archivo de configuración temporal
      run: |
        # Creamos un archivo de configuración específico para GitHub Actions
        cat > github_actions_settings.py << EOF
        # Este archivo es generado automáticamente por GitHub Actions
        # No debe ser añadido al repositorio

        # Importar la configuración base
        import os
        import sys
        from pathlib import Path

        # Cargamos el módulo de configuración original
        sys.path.insert(0, '.')
        os.environ['DJANGO_SETTINGS_MODULE'] = 'alertas_project.settings'

        # Sobreescribimos sólo las variables secretas necesarias
        # No se escribe ningún secreto en el archivo, sólo se asignan variables de entorno
        os.environ['SECRET_KEY'] = "${{ secrets.DJANGO_SECRET_KEY }}"
        os.environ['DATABASE_URL'] = "${{ secrets.DATABASE_URL }}"
        os.environ['DEBUG'] = "False"
        EOF
        
    - name: Ejecutar scrapers con configuración segura
      run: |
        # Configuramos PYTHONPATH para que encuentre nuestro módulo temporal
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        
        # Ejecutamos el comando con el módulo de configuración específico
        DJANGO_SETTINGS_MODULE=github_actions_settings python manage.py run_scrapers --json
        
    - name: Eliminar archivo de configuración
      if: always()
      run: |
        # Siempre eliminamos el archivo de configuración temporal
        rm -f github_actions_settings.py