name: Ejecutar Scrapers

on:
  schedule:
    # Ejecutar cada 6 horas - a las 0:00, 6:00, 12:00 y 18:00 UTC
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:  # Permite ejecutar manualmente el flujo desde la interfaz de GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Ajusta según la versión que necesites

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scrapers
        env:
          # Variables de entorno para Supabase y Django
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          # Añade cualquier otra variable de entorno que necesites
        run: |
          python manage.py run_scrapers  # Necesitarás crear este comando personalizado